import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('ar'), Locale('en')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  bool get isArabic => locale.languageCode == 'ar';

  String get(String key) {
    return _extraValues[locale.languageCode]?[key] ??
        _extraValues['ar']?[key] ??
        _values[locale.languageCode]?[key] ??
        _values['ar']?[key] ??
        key;
  }

  static const _extraValues = <String, Map<String, String>>{
    'ar': {
      'pharmacies': 'الصيدليات',
      'pharmacy': 'الصيدلية',
      'products': 'المنتجات',
      'searchMedicine': 'ابحث عن دواء أو صيدلية',
      'addToCart': 'أضف للسلة',
      'cart': 'السلة',
      'quantity': 'الكمية',
      'remove': 'إزالة',
      'clearCart': 'تفريغ السلة',
      'onePharmacyCartNotice':
          'السلة الحالية تخص صيدلية أخرى. هل تريد تفريغها وبدء طلب جديد؟',
      'approximateTotal': 'إجمالي تقريبي',
      'localSubtotal': 'إجمالي محلي للعرض فقط',
      'pharmacyConfirmsTotal':
          'الأسعار والمبلغ النهائي يتم تأكيدهم من الصيدلية.',
      'requiresPrescription': 'يتطلب روشتة',
      'uploadPrescription': 'رفع روشتة',
      'choosePrescriptionImage': 'اختيار صورة الروشتة',
      'prescriptionUploaded': 'تم رفع الروشتة',
      'prescriptionPrivate':
          'سيتم حفظ الروشتة بشكل خاص ولا تظهر إلا للجهات المصرح لها.',
      'prescriptionRequiredMessage': 'هذا الطلب يحتاج رفع روشتة',
      'createOrder': 'إنشاء الطلب',
      'orderCreated': 'تم إنشاء طلب الصيدلية',
      'pharmacyOrders': 'طلبات الصيدلية',
      'pharmacyOrderDetails': 'تفاصيل طلب الصيدلية',
      'pharmacyReview': 'في مراجعة الصيدلية',
      'awaitingPayment': 'في انتظار الدفع',
      'paid': 'مدفوع',
      'preparing': 'جاري التحضير',
      'ready': 'جاهز',
      'delivered': 'تم التسليم',
      'rejected': 'مرفوض',
      'noProducts': 'لا توجد منتجات',
      'noPharmacies': 'لا توجد صيدليات',
      'noPharmacyOrders': 'لا توجد طلبات صيدلية',
      'orderPayment': 'دفع الطلب',
      'createPayment': 'إنشاء الدفع',
      'pharmacyWaitingReview': 'الطلب في انتظار مراجعة الصيدلية.',
      'items': 'العناصر',
      'createdAt': 'تاريخ الإنشاء',
      'privateFile': 'ملف خاص',
      'cartEmpty': 'السلة فارغة',
      'viewOrders': 'عرض الطلبات',
      'labs': 'المعامل',
      'lab': 'المعمل',
      'tests': 'التحاليل',
      'packages': 'الباقات',
      'searchLabTest': 'ابحث عن تحليل',
      'addToLabOrder': 'أضف للطلب',
      'labOrderCart': 'طلب التحاليل',
      'labConfirmsTotal': 'المبلغ النهائي يتم تأكيده من المعمل.',
      'branchVisit': 'زيارة الفرع',
      'homeCollection': 'سحب عينة من المنزل',
      'homeAddress': 'عنوان المنزل',
      'homeAddressRequired': 'عنوان المنزل مطلوب لسحب العينة من المنزل',
      'createLabOrder': 'إنشاء طلب المعمل',
      'labOrderCreated': 'تم إنشاء طلب المعمل',
      'labOrders': 'طلبات المعمل',
      'labOrderDetails': 'تفاصيل طلب المعمل',
      'labReview': 'في مراجعة المعمل',
      'sampleCollection': 'قيد سحب العينة',
      'labProcessing': 'قيد التحليل',
      'resultReady': 'النتيجة جاهزة',
      'downloadResult': 'تحميل النتيجة',
      'resultDownloaded': 'تم تحميل النتيجة',
      'resultUnavailable': 'النتيجة غير متاحة حاليًا',
      'noLabs': 'لا توجد معامل',
      'noTests': 'لا توجد تحاليل',
      'noPackages': 'لا توجد باقات',
      'noLabOrders': 'لا توجد طلبات معامل',
      'oneLabCartNotice':
          'السلة الحالية تخص معمل آخر. هل تريد تفريغها وبدء طلب جديد؟',
      'labWaitingReview': 'الطلب في انتظار مراجعة المعمل.',
      'sampleCollectionMethod': 'طريقة سحب العينة',
      'labResult': 'نتيجة التحليل',
      'labCartEmpty': 'طلب التحاليل فارغ',
      'health': 'صحتي',
      'healthProfile': 'الملف الصحي',
      'vitals': 'القياسات الصحية',
      'addVital': 'إضافة قياس',
      'latestVitals': 'آخر القياسات',
      'healthSummary': 'ملخص الصحة',
      'bloodPressure': 'ضغط الدم',
      'bloodSugar': 'سكر الدم',
      'heartRate': 'نبض القلب',
      'oxygen': 'الأكسجين',
      'temperature': 'درجة الحرارة',
      'weight': 'الوزن',
      'sleep': 'النوم',
      'mood': 'المزاج',
      'symptoms': 'الأعراض',
      'systolic': 'الانقباضي',
      'diastolic': 'الانبساطي',
      'beforeMeal': 'قبل الأكل',
      'afterMeal': 'بعد الأكل',
      'fasting': 'صائم',
      'random': 'عشوائي',
      'bedtime': 'قبل النوم',
      'sleepHours': 'ساعات النوم',
      'sleepQuality': 'جودة النوم',
      'saveVital': 'حفظ القياس',
      'noVitalsYet': 'لا توجد قياسات حتى الآن',
      'addFirstHealthRecord': 'ابدأ بإضافة أول قياس صحي',
      'healthDisclaimer':
          'هذه البيانات للمتابعة والتنظيم فقط، ولا تعتبر تشخيصًا أو علاجًا طبيًا. إذا كانت لديك أعراض خطيرة أو قراءات مقلقة، تواصل مع طبيب مختص.',
      'repeatedReadingDoctor':
          'إذا كانت القراءة متكررة أو معها أعراض، راجع طبيبًا.',
      'veryLow': 'منخفض جدًا',
      'low': 'منخفض',
      'followUpRange': 'ضمن المتابعة',
      'high': 'مرتفع',
      'veryHigh': 'مرتفع جدًا',
      'unknownFlag': 'غير محدد',
      'measuredAt': 'وقت القياس',
      'now': 'الآن',
      'context': 'السياق',
      'trendPreview': 'ترند المتابعة',
      'trendDisclaimer': 'الترند للمتابعة فقط وليس تشخيصًا',
      'profileCompletion': 'اكتمال الملف',
      'bmi': 'مؤشر الكتلة',
      'followUpFlags': 'تنبيهات متابعة',
      'editProfile': 'تعديل الملف',
      'basicInfo': 'البيانات الأساسية',
      'birthDate': 'تاريخ الميلاد',
      'gender': 'النوع',
      'heightCm': 'الطول (سم)',
      'weightKg': 'الوزن (كجم)',
      'bloodType': 'فصيلة الدم',
      'chronicDiseases': 'الأمراض المزمنة',
      'allergies': 'الحساسيات',
      'currentMedications': 'الأدوية الحالية',
      'surgeries': 'العمليات السابقة',
      'goals': 'الأهداف',
      'save': 'حفظ',
      'profileUpdated': 'تم تحديث الملف الصحي',
      'vitalSaved': 'تم حفظ القياس',
      'veryBad': 'سيئ جدًا',
      'bad': 'سيئ',
      'neutral': 'متوسط',
      'good': 'جيد',
      'veryGood': 'جيد جدًا',
      'unknown': 'غير محدد',
      'all': 'الكل',
      'medications': 'الأدوية',
      'medicationReminders': 'تذكيرات الأدوية',
      'addMedicationReminder': 'إضافة تذكير دواء',
      'medicationName': 'اسم الدواء',
      'dosage': 'الجرعة',
      'dosageUnit': 'وحدة الجرعة',
      'instructions': 'تعليمات',
      'frequency': 'عدد المرات',
      'onceDaily': 'مرة يوميًا',
      'twiceDaily': 'مرتين يوميًا',
      'threeTimesDaily': 'ثلاث مرات يوميًا',
      'customTimes': 'أوقات مخصصة',
      'everyXHours': 'كل عدد ساعات',
      'specificDays': 'أيام محددة',
      'asNeeded': 'عند الحاجة',
      'reminderTimes': 'أوقات التذكير',
      'startDate': 'تاريخ البداية',
      'endDate': 'تاريخ النهاية',
      'todayDoses': 'جرعات اليوم',
      'taken': 'تم أخذها',
      'skipped': 'تم تخطيها',
      'missed': 'فائتة',
      'markTaken': 'تسجيل كأُخذت',
      'markSkipped': 'تسجيل كتخطي',
      'adherence': 'الالتزام',
      'totalDoses': 'إجمالي الجرعات',
      'takenDoses': 'الجرعات المأخوذة',
      'skippedDoses': 'الجرعات المتخطاة',
      'missedDoses': 'الجرعات الفائتة',
      'refill': 'إعادة التعبئة',
      'refillEnabled': 'تذكير إعادة التعبئة مفعل',
      'refillDue': 'موعد إعادة التعبئة',
      'refillDone': 'تمت إعادة التعبئة',
      'refillSkipped': 'تم تخطي إعادة التعبئة',
      'refillDoneAction': 'تم شراء/تعبئة الدواء',
      'refillSkippedAction': 'تخطي إعادة التعبئة',
      'pauseReminder': 'إيقاف مؤقت',
      'resumeReminder': 'استئناف',
      'cancelReminder': 'إلغاء التذكير',
      'medicationDisclaimer':
          'تذكيرات الأدوية للتنظيم فقط، ولا تعتبر وصفة طبية أو نصيحة علاجية. لا توقف أو تغير جرعة أي دواء بدون الرجوع للطبيب أو الصيدلي.',
      'adherenceDisclaimer':
          'هذا الملخص يساعدك على المتابعة فقط ولا يعني نجاح أو فشل علاج طبي.',
      'addFirstMedicationReminder': 'ابدأ بإضافة أول تذكير دواء',
      'activeReminders': 'التذكيرات النشطة',
      'noMedicationReminders': 'لا توجد تذكيرات أدوية',
      'noTodayMedications': 'لا توجد جرعات مجدولة اليوم',
      'noAdherenceYet': 'لا يوجد ملخص التزام بعد',
      'reminderCreated': 'تم إنشاء تذكير الدواء',
      'reminderDetails': 'تفاصيل تذكير الدواء',
      'doseTakenSaved': 'تم تسجيل الجرعة',
      'doseSkippedSaved': 'تم تخطي الجرعة',
      'doseAlreadyLogged': 'تم تسجيل هذه الجرعة',
      'active': 'نشط',
      'paused': 'متوقف مؤقتًا',
      'completed': 'مكتمل',
      'cancelled': 'ملغي',
      'ended': 'منتهي/ملغي',
      'intervalHours': 'عدد الساعات',
      'prescribedBy': 'بواسطة',
      'refillQuantity': 'كمية الدواء',
      'refillThreshold': 'حد التنبيه',
      'refillDate': 'تاريخ تذكير التعبئة',
      'time': 'الوقت',
      'add': 'إضافة',
      'asNeededNoTimes': 'لا يحتاج أوقات ثابتة عند الحاجة',
      'recentLogs': 'آخر التسجيلات',
    },
    'en': {
      'pharmacies': 'Pharmacies',
      'pharmacy': 'Pharmacy',
      'products': 'Products',
      'searchMedicine': 'Search medicine or pharmacy',
      'addToCart': 'Add to cart',
      'cart': 'Cart',
      'quantity': 'Quantity',
      'remove': 'Remove',
      'clearCart': 'Clear cart',
      'onePharmacyCartNotice':
          'The current cart belongs to another pharmacy. Clear it and start a new order?',
      'approximateTotal': 'Approximate total',
      'localSubtotal': 'Local display subtotal',
      'pharmacyConfirmsTotal':
          'Prices and final total are confirmed by the pharmacy.',
      'requiresPrescription': 'Requires prescription',
      'uploadPrescription': 'Upload prescription',
      'choosePrescriptionImage': 'Choose prescription image',
      'prescriptionUploaded': 'Prescription uploaded',
      'prescriptionPrivate':
          'The prescription is stored privately and shown only to authorized parties.',
      'prescriptionRequiredMessage': 'This order requires a prescription',
      'createOrder': 'Create order',
      'orderCreated': 'Pharmacy order created',
      'pharmacyOrders': 'Pharmacy orders',
      'pharmacyOrderDetails': 'Pharmacy order details',
      'pharmacyReview': 'Pharmacy review',
      'awaitingPayment': 'Awaiting payment',
      'paid': 'Paid',
      'preparing': 'Preparing',
      'ready': 'Ready',
      'delivered': 'Delivered',
      'rejected': 'Rejected',
      'noProducts': 'No products',
      'noPharmacies': 'No pharmacies',
      'noPharmacyOrders': 'No pharmacy orders',
      'orderPayment': 'Order payment',
      'createPayment': 'Create payment',
      'pharmacyWaitingReview': 'The order is waiting for pharmacy review.',
      'items': 'Items',
      'createdAt': 'Created at',
      'privateFile': 'Private file',
      'cartEmpty': 'Cart is empty',
      'viewOrders': 'View orders',
      'labs': 'Labs',
      'lab': 'Lab',
      'tests': 'Tests',
      'packages': 'Packages',
      'searchLabTest': 'Search lab test',
      'addToLabOrder': 'Add to order',
      'labOrderCart': 'Lab order',
      'labConfirmsTotal': 'The final amount is confirmed by the lab.',
      'branchVisit': 'Branch visit',
      'homeCollection': 'Home collection',
      'homeAddress': 'Home address',
      'homeAddressRequired': 'Home address is required for home collection',
      'createLabOrder': 'Create lab order',
      'labOrderCreated': 'Lab order created',
      'labOrders': 'Lab orders',
      'labOrderDetails': 'Lab order details',
      'labReview': 'Lab review',
      'sampleCollection': 'Sample collection',
      'labProcessing': 'Processing',
      'resultReady': 'Result ready',
      'downloadResult': 'Download result',
      'resultDownloaded': 'Result downloaded',
      'resultUnavailable': 'Result is unavailable right now',
      'noLabs': 'No labs',
      'noTests': 'No tests',
      'noPackages': 'No packages',
      'noLabOrders': 'No lab orders',
      'oneLabCartNotice':
          'The current cart belongs to another lab. Clear it and start a new order?',
      'labWaitingReview': 'The order is waiting for lab review.',
      'sampleCollectionMethod': 'Sample collection method',
      'labResult': 'Lab result',
      'labCartEmpty': 'Lab order is empty',
      'health': 'Health',
      'healthProfile': 'Health profile',
      'vitals': 'Vitals',
      'addVital': 'Add vital',
      'latestVitals': 'Latest vitals',
      'healthSummary': 'Health summary',
      'bloodPressure': 'Blood pressure',
      'bloodSugar': 'Blood sugar',
      'heartRate': 'Heart rate',
      'oxygen': 'Oxygen',
      'temperature': 'Temperature',
      'weight': 'Weight',
      'sleep': 'Sleep',
      'mood': 'Mood',
      'symptoms': 'Symptoms',
      'systolic': 'Systolic',
      'diastolic': 'Diastolic',
      'beforeMeal': 'Before meal',
      'afterMeal': 'After meal',
      'fasting': 'Fasting',
      'random': 'Random',
      'bedtime': 'Bedtime',
      'sleepHours': 'Sleep hours',
      'sleepQuality': 'Sleep quality',
      'saveVital': 'Save vital',
      'noVitalsYet': 'No vitals yet',
      'addFirstHealthRecord': 'Start by adding your first health record',
      'healthDisclaimer':
          'These records are for tracking and organization only, and are not a medical diagnosis or treatment. If you have serious symptoms or concerning readings, contact a qualified doctor.',
      'repeatedReadingDoctor':
          'If the reading repeats or comes with symptoms, consult a doctor.',
      'veryLow': 'Very low',
      'low': 'Low',
      'followUpRange': 'Within tracking range',
      'high': 'High',
      'veryHigh': 'Very high',
      'unknownFlag': 'Not specified',
      'measuredAt': 'Measured at',
      'now': 'Now',
      'context': 'Context',
      'trendPreview': 'Tracking trend',
      'trendDisclaimer': 'The trend is for tracking only, not diagnosis',
      'profileCompletion': 'Profile completion',
      'bmi': 'BMI',
      'followUpFlags': 'Tracking flags',
      'editProfile': 'Edit profile',
      'basicInfo': 'Basic info',
      'birthDate': 'Birth date',
      'gender': 'Gender',
      'heightCm': 'Height (cm)',
      'weightKg': 'Weight (kg)',
      'bloodType': 'Blood type',
      'chronicDiseases': 'Chronic diseases',
      'allergies': 'Allergies',
      'currentMedications': 'Current medications',
      'surgeries': 'Surgeries',
      'goals': 'Goals',
      'save': 'Save',
      'profileUpdated': 'Health profile updated',
      'vitalSaved': 'Vital saved',
      'veryBad': 'Very bad',
      'bad': 'Bad',
      'neutral': 'Neutral',
      'good': 'Good',
      'veryGood': 'Very good',
      'unknown': 'Unknown',
      'all': 'All',
      'medications': 'Medications',
      'medicationReminders': 'Medication reminders',
      'addMedicationReminder': 'Add medication reminder',
      'medicationName': 'Medication name',
      'dosage': 'Dosage',
      'dosageUnit': 'Dosage unit',
      'instructions': 'Instructions',
      'frequency': 'Frequency',
      'onceDaily': 'Once daily',
      'twiceDaily': 'Twice daily',
      'threeTimesDaily': 'Three times daily',
      'customTimes': 'Custom times',
      'everyXHours': 'Every X hours',
      'specificDays': 'Specific days',
      'asNeeded': 'As needed',
      'reminderTimes': 'Reminder times',
      'startDate': 'Start date',
      'endDate': 'End date',
      'todayDoses': 'Today doses',
      'taken': 'Taken',
      'skipped': 'Skipped',
      'missed': 'Missed',
      'markTaken': 'Mark taken',
      'markSkipped': 'Mark skipped',
      'adherence': 'Adherence',
      'totalDoses': 'Total doses',
      'takenDoses': 'Taken doses',
      'skippedDoses': 'Skipped doses',
      'missedDoses': 'Missed doses',
      'refill': 'Refill',
      'refillEnabled': 'Refill reminder enabled',
      'refillDue': 'Refill due',
      'refillDone': 'Refill done',
      'refillSkipped': 'Refill skipped',
      'refillDoneAction': 'Medication refilled',
      'refillSkippedAction': 'Skip refill',
      'pauseReminder': 'Pause',
      'resumeReminder': 'Resume',
      'cancelReminder': 'Cancel reminder',
      'medicationDisclaimer':
          'Medication reminders are for organization only and are not a prescription or treatment advice. Do not stop or change any medication dose without consulting a doctor or pharmacist.',
      'adherenceDisclaimer':
          'This summary helps follow-up only and does not mean medical treatment success or failure.',
      'addFirstMedicationReminder':
          'Start by adding your first medication reminder',
      'activeReminders': 'Active reminders',
      'noMedicationReminders': 'No medication reminders',
      'noTodayMedications': 'No scheduled doses today',
      'noAdherenceYet': 'No adherence summary yet',
      'reminderCreated': 'Medication reminder created',
      'reminderDetails': 'Medication reminder details',
      'doseTakenSaved': 'Dose recorded',
      'doseSkippedSaved': 'Dose skipped',
      'doseAlreadyLogged': 'This dose was already logged',
      'active': 'Active',
      'paused': 'Paused',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'ended': 'Ended/cancelled',
      'intervalHours': 'Interval hours',
      'prescribedBy': 'Prescribed by',
      'refillQuantity': 'Refill quantity',
      'refillThreshold': 'Refill threshold',
      'refillDate': 'Refill reminder date',
      'time': 'Time',
      'add': 'Add',
      'asNeededNoTimes': 'No fixed times are required for as-needed reminders',
      'recentLogs': 'Recent logs',
    },
  };

  static const _values = <String, Map<String, String>>{
    'ar': {
      'appName': 'اطمن',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'phone': 'رقم الهاتف',
      'confirmPassword': 'تأكيد كلمة المرور',
      'requiredField': 'هذا الحقل مطلوب',
      'invalidEmail': 'اكتب بريدًا إلكترونيًا صحيحًا',
      'passwordMin': 'كلمة المرور يجب ألا تقل عن 8 أحرف',
      'passwordMismatch': 'كلمتا المرور غير متطابقتين',
      'home': 'الرئيسية',
      'doctors': 'الأطباء',
      'account': 'الحساب',
      'logout': 'تسجيل الخروج',
      'retry': 'إعادة المحاولة',
      'refresh': 'تحديث',
      'loading': 'جاري التحميل...',
      'emptyDoctors': 'لا يوجد أطباء متاحون حاليًا',
      'emptySlots': 'لا توجد مواعيد متاحة',
      'serverUnavailable': 'الاتصال بالسيرفر غير متاح حاليًا',
      'unexpectedError': 'حدث خطأ غير متوقع',
      'sessionExpired': 'انتهت الجلسة، سجل دخول مرة أخرى',
      'forbidden': 'ليس لديك صلاحية لتنفيذ هذا الإجراء',
      'rateLimited': 'طلبات كثيرة، حاول بعد قليل',
      'bookAppointment': 'احجز موعد',
      'availableSlots': 'المواعيد المتاحة',
      'consultationType': 'نوع الكشف',
      'clinic': 'في العيادة',
      'online': 'أونلاين',
      'problemDescription': 'وصف المشكلة اختياري',
      'confirmBooking': 'تأكيد الحجز',
      'bookingConfirmed': 'تم تأكيد الحجز',
      'bookingPendingPayment': 'الحجز في انتظار الدفع',
      'paymentLater': 'الدفع سيتم تفعيله في Sprint لاحق',
      'slotNoLongerAvailable': 'الموعد لم يعد متاحًا، اختر موعدًا آخر',
      'fee': 'الكشف',
      'rating': 'التقييم',
      'specialties': 'التخصصات',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'paymentMethods': 'طرق الدفع',
      'choosePaymentMethod': 'اختر طريقة الدفع',
      'paymentMethod': 'طريقة الدفع',
      'manualPaymentSubtitle': 'حوّل المبلغ ثم ارفع إثبات الدفع للمراجعة',
      'paymobSubtitle': 'دفع إلكتروني عبر Paymob من خلال الباكند',
      'paymentSummary': 'ملخص الدفع',
      'paymentAdminReviewNotice':
          'الدفع اليدوي تتم مراجعته من الإدارة قبل تأكيد الموعد.',
      'emptyPaymentMethods': 'لا توجد طرق دفع متاحة حاليًا',
      'paymentStatusUnavailable': 'تعذر تحميل حالة الدفع الآن',
      'appointmentStatus': 'حالة الموعد',
      'goToPayment': 'اذهب للدفع',
      'bookingPaymentMissing':
          'تم إنشاء الحجز لكن لم يتم العثور على بيانات الدفع، حاول تحديث الحالة أو تواصل مع الدعم',
      'amount': 'المبلغ',
      'manualInstructions': 'تعليمات الدفع',
      'instructionsUnavailable': 'تعليمات الدفع غير متاحة حاليًا',
      'uploadProof': 'رفع إثبات الدفع',
      'proofUploadHint': 'اختر صورة واضحة للتحويل. لا يتم حفظ المسار المحلي.',
      'chooseProofImage': 'اختيار صورة الإثبات',
      'removeFile': 'إزالة الملف',
      'referenceNumber': 'رقم العملية اختياري',
      'senderPhone': 'رقم المحوّل اختياري',
      'notes': 'ملاحظات',
      'submitProof': 'إرسال الإثبات',
      'proofRequired': 'اختر صورة إثبات الدفع أولًا',
      'fileTooLarge': 'حجم الملف كبير، اختر صورة أصغر',
      'proofUploaded': 'تم رفع إثبات الدفع، سيتم مراجعته قريبًا',
      'doNotCloseBeforeProof': 'لا تغلق التطبيق قبل رفع إثبات الدفع',
      'paymentStatus': 'حالة الدفع',
      'checkPaymentStatus': 'تحقق من حالة الدفع',
      'paymentPollingMessage':
          'نراجع حالة الدفع كل بضع ثوانٍ بدون إزعاج السيرفر.',
      'waitingAdminReview': 'في انتظار مراجعة الإدارة لإثبات الدفع.',
      'waitingGatewayConfirmation': 'في انتظار تأكيد بوابة الدفع من الباكند.',
      'paymentAndAppointmentConfirmed': 'تم تأكيد الدفع والموعد',
      'paymentRejectedRetry': 'تم رفض إثبات الدفع، يمكنك إعادة المحاولة',
      'retryProof': 'إعادة رفع إثبات الدفع',
      'viewAppointment': 'عرض الموعد',
      'backHome': 'العودة للرئيسية',
      'lastUpdated': 'آخر تحديث',
      'onlinePayment': 'دفع إلكتروني',
      'paymobCheckoutTitle': 'الدفع الإلكتروني عبر Paymob',
      'paymobCheckoutSafety':
          'سيتم فتح صفحة الدفع الآمنة التي أنشأها الباكند فقط.',
      'paymobRedirectNotProof':
          'الرجوع من صفحة الدفع ليس دليلًا على النجاح؛ سنراجع حالة الدفع من الباكند.',
      'openPaymentPage': 'افتح صفحة الدفع',
      'createPaymobSession': 'إنشاء جلسة الدفع',
      'paymobMissingCheckoutUrl':
          'الباكند لم يرجع رابط checkout. قد يحتاج إعداد Paymob الحقيقي.',
      'cannotOpenPaymentPage': 'تعذر فتح صفحة الدفع',
      'paymentDraft': 'مسودة',
      'awaitingMethod': 'اختر طريقة الدفع',
      'awaitingProof': 'بانتظار إثبات الدفع',
      'pendingReview': 'في انتظار المراجعة',
      'pendingGateway': 'جاري الدفع الإلكتروني',
      'paymentVerified': 'تم تأكيد الدفع',
      'paymentRejected': 'تم رفض الدفع',
      'paymentFailed': 'فشل الدفع',
      'paymentExpired': 'انتهت صلاحية الدفع',
      'paymentCancelled': 'تم إلغاء الدفع',
      'paymentRefunded': 'تم الاسترداد',
      'unknownStatus': 'حالة غير معروفة',
      'myAppointments': 'مواعيدي',
      'emptyAppointments': 'لا توجد مواعيد حتى الآن',
      'all': 'الكل',
      'upcoming': 'القادمة',
      'completed': 'مكتملة',
      'cancelled': 'ملغية',
      'viewDetails': 'عرض التفاصيل',
      'payNow': 'ادفع الآن',
      'continuePayment': 'متابعة الدفع',
      'appointmentDetails': 'تفاصيل الموعد',
      'cancelAppointment': 'إلغاء الموعد',
      'confirmCancelAppointment': 'هل أنت متأكد من إلغاء الموعد؟',
      'cancelReason': 'سبب الإلغاء اختياري',
      'appointmentCancelledDone': 'تم إلغاء الموعد',
      'cannotCancelAppointment': 'لا يمكن إلغاء هذا الموعد',
      'paidCancellationBlocked':
          'لا يمكن إلغاء موعد مدفوع من التطبيق حاليًا، تواصل مع الدعم.',
      'paymentDone': 'تم الدفع',
      'noAdditionalDetails': 'لا توجد تفاصيل إضافية',
      'appointmentTimeline': 'سجل حالة الموعد',
      'appointmentTime': 'وقت الموعد',
      'location': 'المكان',
      'doctor': 'الطبيب',
      'dateUnavailable': 'الموعد غير محدد',
      'noPaymentRequired': 'لا يوجد دفع مطلوب',
      'back': 'رجوع',
      'appointmentDraft': 'مسودة',
      'pendingPayment': 'في انتظار الدفع',
      'pendingPaymentReview': 'في انتظار مراجعة الدفع',
      'appointmentConfirmed': 'مؤكد',
      'appointmentAccepted': 'مقبول',
      'appointmentRejected': 'مرفوض',
      'appointmentCancelled': 'ملغي',
      'cancelledByPatient': 'ملغي من المريض',
      'cancelledByDoctor': 'ملغي من الطبيب',
      'appointmentCompleted': 'مكتمل',
      'appointmentNoShow': 'لم يحضر',
      'appointmentExpired': 'منتهي',
    },
    'en': {
      'appName': 'Etamen',
      'login': 'Login',
      'register': 'Create account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'phone': 'Phone',
      'confirmPassword': 'Confirm password',
      'requiredField': 'This field is required',
      'invalidEmail': 'Enter a valid email',
      'passwordMin': 'Password must be at least 8 characters',
      'passwordMismatch': 'Passwords do not match',
      'home': 'Home',
      'doctors': 'Doctors',
      'account': 'Account',
      'logout': 'Logout',
      'retry': 'Retry',
      'refresh': 'Refresh',
      'loading': 'Loading...',
      'emptyDoctors': 'No doctors are available right now',
      'emptySlots': 'No available slots',
      'serverUnavailable': 'Cannot connect to the server',
      'unexpectedError': 'Something went wrong',
      'sessionExpired': 'Session expired, please login again',
      'forbidden': 'You do not have permission',
      'rateLimited': 'Too many requests, try again later',
      'bookAppointment': 'Book appointment',
      'availableSlots': 'Available slots',
      'consultationType': 'Consultation type',
      'clinic': 'Clinic',
      'online': 'Online',
      'problemDescription': 'Problem description optional',
      'confirmBooking': 'Confirm booking',
      'bookingConfirmed': 'Booking confirmed',
      'bookingPendingPayment': 'Booking is pending payment',
      'paymentLater': 'Payment will be enabled in a later sprint',
      'slotNoLongerAvailable': 'This slot is no longer available',
      'fee': 'Fee',
      'rating': 'Rating',
      'specialties': 'Specialties',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'paymentMethods': 'Payment methods',
      'choosePaymentMethod': 'Choose payment method',
      'paymentMethod': 'Payment method',
      'manualPaymentSubtitle': 'Transfer then upload proof for admin review',
      'paymobSubtitle': 'Online payment through backend-created Paymob session',
      'paymentSummary': 'Payment summary',
      'paymentAdminReviewNotice':
          'Manual payments are reviewed by admin before confirming the appointment.',
      'emptyPaymentMethods': 'No payment methods are available now',
      'paymentStatusUnavailable': 'Payment status is unavailable now',
      'appointmentStatus': 'Appointment status',
      'goToPayment': 'Go to payment',
      'bookingPaymentMissing':
          'Booking was created but payment data was not found. Refresh status or contact support.',
      'amount': 'Amount',
      'manualInstructions': 'Payment instructions',
      'instructionsUnavailable': 'Payment instructions are unavailable',
      'uploadProof': 'Upload payment proof',
      'proofUploadHint':
          'Choose a clear transfer screenshot. The local path is not stored.',
      'chooseProofImage': 'Choose proof image',
      'removeFile': 'Remove file',
      'referenceNumber': 'Reference number optional',
      'senderPhone': 'Sender phone optional',
      'notes': 'Notes',
      'submitProof': 'Submit proof',
      'proofRequired': 'Choose a payment proof image first',
      'fileTooLarge': 'File is too large, choose a smaller image',
      'proofUploaded': 'Payment proof uploaded and will be reviewed soon',
      'doNotCloseBeforeProof': 'Do not close the app before uploading proof',
      'paymentStatus': 'Payment status',
      'checkPaymentStatus': 'Check payment status',
      'paymentPollingMessage':
          'We check payment status every few seconds without spamming the server.',
      'waitingAdminReview': 'Waiting for admin review.',
      'waitingGatewayConfirmation':
          'Waiting for gateway confirmation from backend.',
      'paymentAndAppointmentConfirmed': 'Payment and appointment confirmed',
      'paymentRejectedRetry': 'Payment proof was rejected. You can try again.',
      'retryProof': 'Upload proof again',
      'viewAppointment': 'View appointment',
      'backHome': 'Back home',
      'lastUpdated': 'Last updated',
      'onlinePayment': 'Online payment',
      'paymobCheckoutTitle': 'Paymob online payment',
      'paymobCheckoutSafety':
          'Only the backend-created checkout page will be opened.',
      'paymobRedirectNotProof':
          'Returning from checkout is not proof of payment; backend status remains the source of truth.',
      'openPaymentPage': 'Open payment page',
      'createPaymobSession': 'Create payment session',
      'paymobMissingCheckoutUrl':
          'Backend did not return a checkout URL. Real Paymob config may be missing.',
      'cannotOpenPaymentPage': 'Cannot open payment page',
      'paymentDraft': 'Draft',
      'awaitingMethod': 'Awaiting method',
      'awaitingProof': 'Awaiting proof',
      'pendingReview': 'Pending review',
      'pendingGateway': 'Pending gateway',
      'paymentVerified': 'Payment verified',
      'paymentRejected': 'Payment rejected',
      'paymentFailed': 'Payment failed',
      'paymentExpired': 'Payment expired',
      'paymentCancelled': 'Payment cancelled',
      'paymentRefunded': 'Payment refunded',
      'unknownStatus': 'Unknown status',
      'myAppointments': 'My appointments',
      'emptyAppointments': 'No appointments yet',
      'all': 'All',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'viewDetails': 'View details',
      'payNow': 'Pay now',
      'continuePayment': 'Continue payment',
      'appointmentDetails': 'Appointment details',
      'cancelAppointment': 'Cancel appointment',
      'confirmCancelAppointment':
          'Are you sure you want to cancel this appointment?',
      'cancelReason': 'Cancellation reason optional',
      'appointmentCancelledDone': 'Appointment cancelled',
      'cannotCancelAppointment': 'This appointment cannot be cancelled',
      'paidCancellationBlocked':
          'Paid appointments cannot be cancelled from the app right now. Contact support.',
      'paymentDone': 'Paid',
      'noAdditionalDetails': 'No additional details',
      'appointmentTimeline': 'Appointment timeline',
      'appointmentTime': 'Appointment time',
      'location': 'Location',
      'doctor': 'Doctor',
      'dateUnavailable': 'Date unavailable',
      'noPaymentRequired': 'No payment required',
      'back': 'Back',
      'appointmentDraft': 'Draft',
      'pendingPayment': 'Pending payment',
      'pendingPaymentReview': 'Payment review',
      'appointmentConfirmed': 'Confirmed',
      'appointmentAccepted': 'Accepted',
      'appointmentRejected': 'Rejected',
      'appointmentCancelled': 'Cancelled',
      'cancelledByPatient': 'Cancelled by patient',
      'cancelledByDoctor': 'Cancelled by doctor',
      'appointmentCompleted': 'Completed',
      'appointmentNoShow': 'No show',
      'appointmentExpired': 'Expired',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((item) => item.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
